// ============================================
// ACHIEVEMENTS MODULE TYPES
// ============================================

export type AchievementType = 'micro' | 'macro' | 'breakthrough' | 'moment'
export type AchievementCategory = 'work' | 'health' | 'personal' | 'skill' | 'finance' | 'relationships' | 'other'
export type EmotionTag = 'proud' | 'relieved' | 'excited' | 'grateful' | 'surprised' | 'scared' | 'joyful'
export type SourceType = 'goal' | 'skill' | 'habit' | 'health' | 'finance' | 'task' | 'manual'

export interface Achievement {
  id: string
  userId: string
  
  // Basic Info
  title: string
  description?: string
  
  // Categorization
  category?: AchievementCategory
  type: AchievementType
  
  // Date & Time
  achievementDate: string // ISO date
  achievementTime?: string // HH:mm
  
  // Emotional & Reflection
  emotionTag?: EmotionTag
  lessonLearned?: string
  
  // Media
  mediaUrls: string[]
  coverImageIndex: number
  
  // Special Flags
  isAutoGenerated: boolean
  isTimeCapsule: boolean
  unlockDate?: string // ISO datetime
  isFavorite: boolean
  
  // Visibility
  isPrivate: boolean
  shareToken?: string
  
  // Gamification
  xpAwarded: number
  badgeIcon: string
  badgeColor: string
  
  // Metadata
  createdAt: string
  updatedAt?: string
  
  // Relations
  links?: AchievementLink[]
  collections?: string[] // collection IDs
}

export interface AchievementLink {
  id: string
  achievementId: string
  userId: string
  sourceType: SourceType
  sourceId?: string
  sourceTitle?: string
  linkDescription?: string
  createdAt: string
}

export interface AchievementCollection {
  id: string
  userId: string
  name: string
  description?: string
  icon: string
  color: string
  isDefault: boolean
  sortOrder: number
  createdAt: string
  updatedAt?: string
  
  // Computed
  achievementCount?: number
}

export interface AchievementCollectionItem {
  id: string
  achievementId: string
  collectionId: string
  userId: string
  addedAt: string
  note?: string
}

export interface AchievementStats {
  id: string
  userId: string
  totalCount: number
  microCount: number
  macroCount: number
  breakthroughCount: number
  momentCount: number
  favoriteCount: number
  timeCapsuleCount: number
  timeCapsuleUnlockedCount: number
  currentStreakDays: number
  longestStreakDays: number
  lastAchievementDate?: string
  updatedAt?: string
}

// ============================================
// UI TYPES
// ============================================

export interface AchievementFilters {
  types?: AchievementType[]
  categories?: AchievementCategory[]
  dateFrom?: string
  dateTo?: string
  isFavorite?: boolean
  isTimeCapsule?: boolean
  searchQuery?: string
  collectionId?: string
}

export interface AchievementSort {
  field: 'date' | 'title' | 'type' | 'created'
  direction: 'asc' | 'desc'
}

// ============================================
// CONSTANTS
// ============================================

export const ACHIEVEMENT_TYPE_CONFIG: Record<AchievementType, {
  label: string
  labelRu: string
  icon: string
  color: string
  description: string
}> = {
  micro: {
    label: 'Micro Win',
    labelRu: 'Микро-победа',
    icon: 'zap',
    color: '#22c55e',
    description: 'Маленькие, но важные шаги вперед'
  },
  macro: {
    label: 'Major Goal',
    labelRu: 'Крупная цель',
    icon: 'trophy',
    color: '#3b82f6',
    description: 'Значимые достижения и долгосрочные цели'
  },
  breakthrough: {
    label: 'Breakthrough',
    labelRu: 'Прорыв',
    icon: 'star',
    color: '#8b5cf6',
    description: 'Преодоление страхов и личных ограничений'
  },
  moment: {
    label: 'Magic Moment',
    labelRu: 'Магический момент',
    icon: 'sparkles',
    color: '#f59e0b',
    description: 'Спонтанные радостные моменты'
  }
}

export const ACHIEVEMENT_CATEGORY_CONFIG: Record<AchievementCategory, {
  label: string
  labelRu: string
  icon: string
  color: string
}> = {
  work: { label: 'Work', labelRu: 'Работа', icon: 'briefcase', color: '#3b82f6' },
  health: { label: 'Health', labelRu: 'Здоровье', icon: 'heart', color: '#22c55e' },
  personal: { label: 'Personal', labelRu: 'Личное', icon: 'user', color: '#ec4899' },
  skill: { label: 'Skill', labelRu: 'Навык', icon: 'sparkles', color: '#f59e0b' },
  finance: { label: 'Finance', labelRu: 'Финансы', icon: 'wallet', color: '#14b8a6' },
  relationships: { label: 'Relationships', labelRu: 'Отношения', icon: 'users', color: '#f97316' },
  other: { label: 'Other', labelRu: 'Другое', icon: 'circle', color: '#6b7280' }
}

export const EMOTION_TAG_CONFIG: Record<EmotionTag, {
  label: string
  labelRu: string
  emoji: string
  color: string
}> = {
  proud: { label: 'Proud', labelRu: 'Гордость', emoji: '🦁', color: '#f59e0b' },
  relieved: { label: 'Relieved', labelRu: 'Облегчение', emoji: '😌', color: '#22c55e' },
  excited: { label: 'Excited', labelRu: 'Восторг', emoji: '🤩', color: '#ec4899' },
  grateful: { label: 'Grateful', labelRu: 'Благодарность', emoji: '🙏', color: '#8b5cf6' },
  surprised: { label: 'Surprised', labelRu: 'Удивление', emoji: '😲', color: '#3b82f6' },
  scared: { label: 'Scared', labelRu: 'Страх', emoji: '😰', color: '#ef4444' },
  joyful: { label: 'Joyful', labelRu: 'Радость', emoji: '😄', color: '#eab308' }
}

// ============================================
// FORM TYPES
// ============================================

export interface CreateAchievementInput {
  title: string
  description?: string
  category?: AchievementCategory
  type: AchievementType
  achievementDate: string
  achievementTime?: string
  emotionTag?: EmotionTag
  lessonLearned?: string
  mediaUrls?: string[]
  isTimeCapsule?: boolean
  unlockDate?: string
  isFavorite?: boolean
  isPrivate?: boolean
  links?: { sourceType: SourceType; sourceId?: string; sourceTitle?: string }[]
  collectionIds?: string[]
}

export interface UpdateAchievementInput extends Partial<CreateAchievementInput> {
  id: string
}

// ============================================
// STATS HELPERS
// ============================================

export function getAchievementTypeColor(type: AchievementType): string {
  return ACHIEVEMENT_TYPE_CONFIG[type].color
}

export function getAchievementTypeLabel(type: AchievementType): string {
  return ACHIEVEMENT_TYPE_CONFIG[type].labelRu
}

export function getAchievementTypeIcon(type: AchievementType): string {
  return ACHIEVEMENT_TYPE_CONFIG[type].icon
}

export function getCategoryLabel(category: AchievementCategory): string {
  return ACHIEVEMENT_CATEGORY_CONFIG[category].labelRu
}

export function getEmotionLabel(emotion: EmotionTag): string {
  return EMOTION_TAG_CONFIG[emotion].labelRu
}

export function getEmotionEmoji(emotion: EmotionTag): string {
  return EMOTION_TAG_CONFIG[emotion].emoji
}
