// ============================================
// GOALS & PROJECTS
// ============================================

import type { Goal, Project } from "@/lib/types"
import { getStore, setStore, KEYS, mutateKey, genId, today } from "./core"
import { addXp } from "./gamification"
import { addToQueue } from "@/lib/sync/offline-first"
import { createAchievement } from "@/lib/store/modules/achievements"

// Goals
export function getGoals(): Goal[] {
  return getStore(KEYS.goals, [])
}

export function addGoal(goal: Omit<Goal, "id" | "createdAt">) {
  const goals = getGoals()
  const newGoal: Goal = { 
    ...goal, 
    id: genId(),
    milestones: goal.milestones || [],
  }
  const updatedGoals = [...goals, newGoal]
  setStore(KEYS.goals, updatedGoals)
  mutateKey(KEYS.goals, updatedGoals)
  
  // Sync to server
  addToQueue({ 
    table: "goals", 
    operation: "insert", 
    recordId: newGoal.id, 
    data: newGoal as Record<string, unknown> 
  })
  
  addXp(50, "goal_created")
  return newGoal
}

export function updateGoal(id: string, updates: Partial<Goal>) {
  const goals = getGoals()
  const goal = goals.find(g => g.id === id)
  if (!goal) return
  
  const updated = { ...goal, ...updates }
  
  // Auto-complete if progress 100
  if (updated.progress >= 100 && !updated.completedAt) {
    updated.status = "completed"
    updated.completedAt = today()
    updated.progress = 100
    addXp(200 + (updated.priority * 50), "goal_completed")
    createAchievement({
      title: `Цель достигнута: ${updated.title}`,
      description: updated.description,
      type: updated.priority >= 4 ? "breakthrough" : "macro",
      achievementDate: today(),
      isAutoGenerated: true,
      links: [{ sourceType: "goal", sourceId: updated.id, sourceTitle: updated.title }],
    })
  }
  
  const updatedGoals = goals.map(g => g.id === id ? updated : g)
  setStore(KEYS.goals, updatedGoals)
  mutateKey(KEYS.goals, updatedGoals)
  
  // Sync to server
  addToQueue({ 
    table: "goals", 
    operation: "update", 
    recordId: id, 
    data: updated as Record<string, unknown> 
  })
}

export function deleteGoal(id: string) {
  const goals = getGoals()
  const updatedGoals = goals.filter(g => g.id !== id)
  setStore(KEYS.goals, updatedGoals)
  mutateKey(KEYS.goals, updatedGoals)
  
  // Sync to server
  addToQueue({ 
    table: "goals", 
    operation: "delete", 
    recordId: id 
  })
}

// Projects
export function getProjects(): Project[] {
  return getStore(KEYS.projects, [])
}

export function addProject(project: Omit<Project, "id" | "createdAt" | "updatedAt">) {
  const projects = getProjects()
  const ts = new Date().toISOString()
  const newProject: Project = {
    ...project,
    id: genId(),
    createdAt: ts,
    updatedAt: ts,
  }
  const updatedProjects = [...projects, newProject]
  setStore(KEYS.projects, updatedProjects)
  mutateKey(KEYS.projects, updatedProjects)

  // Sync to server
  addToQueue({
    table: "projects",
    operation: "insert",
    recordId: newProject.id,
    data: newProject as Record<string, unknown>
  })

  return newProject
}

export function updateProject(id: string, updates: Partial<Project>) {
  const projects = getProjects()
  const project = projects.find(p => p.id === id)
  if (!project) return
  
  const updated = { ...project, ...updates }
  const updatedProjects = projects.map(p => p.id === id ? updated : p)
  setStore(KEYS.projects, updatedProjects)
  mutateKey(KEYS.projects, updatedProjects)
  
  // Sync to server
  addToQueue({ 
    table: "projects", 
    operation: "update", 
    recordId: id, 
    data: updated as Record<string, unknown> 
  })
}

export function deleteProject(id: string) {
  const projects = getProjects()
  const updatedProjects = projects.filter(p => p.id !== id)
  setStore(KEYS.projects, updatedProjects)
  mutateKey(KEYS.projects, updatedProjects)
  
  // Sync to server
  addToQueue({ 
    table: "projects", 
    operation: "delete", 
    recordId: id 
  })
}

export function completeProject(id: string) {
  const projects = getProjects()
  const project = projects.find(p => p.id === id)
  if (!project || project.status === "completed") return
  
  const xpReward = project.xpAwarded || project.priority * 50
  const coinReward = project.priority * 20

  addXp(xpReward, "project_completed")
  
  const updatedProject = { 
    ...project, 
    status: "completed" as const, 
    completedAt: today() 
  }
  
  setStore(KEYS.projects, projects.map(p => 
    p.id === id ? updatedProject : p
  ))
  mutateKey(KEYS.projects)
  
  // Sync to server
  addToQueue({ 
    table: "projects", 
    operation: "update", 
    recordId: id, 
    data: updatedProject as Record<string, unknown> 
  })
}
